name: Static Code Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  static-analysis:
    name: Run Static Code Analysis with Cargo Clippy and Cargo Audit
    runs-on: ubuntu-latest
    steps:
      # Checkout des Codes
      - name: Checkout Code
        uses: actions/checkout@v3

      # Einrichtung der Rust-Toolchain
      - name: Set up Rust Toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      # Install Cargo Audit
      - name: Install Cargo Audit
        run: cargo install cargo-audit

      # Ausführen von Cargo Clippy und Speichern des Berichts
      - name: Run Cargo Clippy and Save Report
        run: |
          cargo clippy --all-targets --all-features -- -D warnings 2>&1 | tee clippy_report.txt

      # Ausführen von Cargo Audit und Speichern des Berichts
      - name: Run Cargo Audit and Save Report
        run: |
          cargo audit 2>&1 | tee cargo_audit_report.txt

      # Hochladen des Clippy-Berichts als Artifact
      - name: Upload Clippy Report
        uses: actions/upload-artifact@v3
        with:
          name: clippy-report
          path: clippy_report.txt

      # Hochladen des Cargo Audit-Berichts als Artifact
      - name: Upload Cargo Audit Report
        uses: actions/upload-artifact@v3
        with:
          name: cargo-audit-report
          path: cargo_audit_report.txt

